// Auto-generated from currency-codes library — do not edit manually
// Run: node scripts/generate-currencies.cjs
export interface CurrencyInfo { code: string; symbol: string; name: string; flag: string; locale: string; }

export const CURRENCIES: CurrencyInfo[] = [
  { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham', flag: '🇦🇪', locale: 'en-US' },
  { code: 'AFN', symbol: '؋', name: 'Afghani', flag: '🇦🇫', locale: 'en-US' },
  { code: 'ALL', symbol: 'L', name: 'Lek', flag: '🇦🇱', locale: 'en-US' },
  { code: 'AMD', symbol: '֏', name: 'Armenian Dram', flag: '🇦🇲', locale: 'en-US' },
  { code: 'ANG', symbol: 'ƒ', name: 'Netherlands Antillean Guilder', flag: '🇨🇼', locale: 'en-US' },
  { code: 'AOA', symbol: 'Kz', name: 'Kwanza', flag: '🇦🇴', locale: 'en-US' },
  { code: 'ARS', symbol: 'AR$', name: 'Argentine Peso', flag: '🇦🇷', locale: 'en-US' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', flag: '🇦🇺', locale: 'en-AU' },
  { code: 'AWG', symbol: 'ƒ', name: 'Aruban Florin', flag: '🇦🇼', locale: 'en-US' },
  { code: 'AZN', symbol: '₼', name: 'Azerbaijan Manat', flag: '🇦🇿', locale: 'en-US' },
  { code: 'BAM', symbol: 'KM', name: 'Convertible Mark', flag: '🇧🇦', locale: 'en-US' },
  { code: 'BBD', symbol: '$', name: 'Barbados Dollar', flag: '🇧🇧', locale: 'en-US' },
  { code: 'BDT', symbol: '৳', name: 'Taka', flag: '🇧🇩', locale: 'en-US' },
  { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev', flag: '🇧🇬', locale: 'en-US' },
  { code: 'BHD', symbol: '.د.ب', name: 'Bahraini Dinar', flag: '🇧🇭', locale: 'en-US' },
  { code: 'BIF', symbol: 'FBu', name: 'Burundi Franc', flag: '🇧🇮', locale: 'en-US' },
  { code: 'BMD', symbol: '$', name: 'Bermudian Dollar', flag: '🇧🇲', locale: 'en-US' },
  { code: 'BND', symbol: '$', name: 'Brunei Dollar', flag: '🇧🇳', locale: 'en-US' },
  { code: 'BOB', symbol: 'Bs', name: 'Boliviano', flag: '🇧🇴', locale: 'en-US' },
  { code: 'BRL', symbol: 'R$', name: 'Brazilian Real', flag: '🇧🇷', locale: 'en-US' },
  { code: 'BSD', symbol: '$', name: 'Bahamian Dollar', flag: '🇧🇸', locale: 'en-US' },
  { code: 'BTN', symbol: 'Nu.', name: 'Ngultrum', flag: '🇧🇹', locale: 'en-US' },
  { code: 'BWP', symbol: 'P', name: 'Pula', flag: '🇧🇼', locale: 'en-US' },
  { code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble', flag: '🇧🇾', locale: 'en-US' },
  { code: 'BZD', symbol: '$', name: 'Belize Dollar', flag: '🇧🇿', locale: 'en-US' },
  { code: 'CAD', symbol: 'CA$', name: 'Canadian Dollar', flag: '🇨🇦', locale: 'en-CA' },
  { code: 'CDF', symbol: 'FC', name: 'Congolese Franc', flag: '🇨🇩', locale: 'en-US' },
  { code: 'CHF', symbol: 'Fr', name: 'Swiss Franc', flag: '🇱🇮', locale: 'de-CH' },
  { code: 'CLP', symbol: '$', name: 'Chilean Peso', flag: '🇨🇱', locale: 'en-US' },
  { code: 'CNY', symbol: '¥', name: 'Yuan Renminbi', flag: '🇨🇳', locale: 'zh-CN' },
  { code: 'COP', symbol: 'COL$', name: 'Colombian Peso', flag: '🇨🇴', locale: 'en-US' },
  { code: 'CRC', symbol: '₡', name: 'Costa Rican Colon', flag: '🇨🇷', locale: 'en-US' },
  { code: 'CUC', symbol: 'CUC', name: 'Peso Convertible', flag: '🇨🇺', locale: 'en-US' },
  { code: 'CUP', symbol: '₱', name: 'Cuban Peso', flag: '🇨🇺', locale: 'en-US' },
  { code: 'CVE', symbol: '$', name: 'Cabo Verde Escudo', flag: '🇨🇻', locale: 'en-US' },
  { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna', flag: '🇨🇿', locale: 'en-US' },
  { code: 'DJF', symbol: 'Fdj', name: 'Djibouti Franc', flag: '🇩🇯', locale: 'en-US' },
  { code: 'DKK', symbol: 'kr', name: 'Danish Krone', flag: '🇩🇰', locale: 'en-US' },
  { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso', flag: '🇩🇴', locale: 'en-US' },
  { code: 'DZD', symbol: 'DZD', name: 'Algerian Dinar', flag: '🇩🇿', locale: 'en-US' },
  { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound', flag: '🇪🇬', locale: 'en-US' },
  { code: 'ERN', symbol: 'Nfk', name: 'Nakfa', flag: '🇪🇷', locale: 'en-US' },
  { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr', flag: '🇪🇹', locale: 'en-US' },
  { code: 'EUR', symbol: '€', name: 'Euro', flag: '🇪🇺', locale: 'fr-FR' },
  { code: 'FJD', symbol: '$', name: 'Fiji Dollar', flag: '🇫🇯', locale: 'en-US' },
  { code: 'FKP', symbol: '£', name: 'Falkland Islands Pound', flag: '🇫🇰', locale: 'en-US' },
  { code: 'GBP', symbol: '£', name: 'Pound Sterling', flag: '🇬🇧', locale: 'en-GB' },
  { code: 'GEL', symbol: '₾', name: 'Lari', flag: '🇬🇪', locale: 'en-US' },
  { code: 'GHS', symbol: '₵', name: 'Ghana Cedi', flag: '🇬🇭', locale: 'en-US' },
  { code: 'GIP', symbol: '£', name: 'Gibraltar Pound', flag: '🇬🇮', locale: 'en-US' },
  { code: 'GMD', symbol: 'D', name: 'Dalasi', flag: '🇬🇲', locale: 'en-US' },
  { code: 'GNF', symbol: 'FG', name: 'Guinean Franc', flag: '🇬🇳', locale: 'en-US' },
  { code: 'GTQ', symbol: 'Q', name: 'Quetzal', flag: '🇬🇹', locale: 'en-US' },
  { code: 'GYD', symbol: '$', name: 'Guyana Dollar', flag: '🇬🇾', locale: 'en-US' },
  { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar', flag: '🇭🇰', locale: 'en-US' },
  { code: 'HNL', symbol: 'L', name: 'Lempira', flag: '🇭🇳', locale: 'en-US' },
  { code: 'HTG', symbol: 'G', name: 'Gourde', flag: '🇭🇹', locale: 'en-US' },
  { code: 'HUF', symbol: 'Ft', name: 'Forint', flag: '🇭🇺', locale: 'en-US' },
  { code: 'IDR', symbol: 'Rp', name: 'Rupiah', flag: '🇮🇩', locale: 'en-US' },
  { code: 'ILS', symbol: '₪', name: 'New Israeli Sheqel', flag: '🇮🇱', locale: 'en-US' },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee', flag: '🇧🇹', locale: 'en-US' },
  { code: 'IQD', symbol: 'IQD', name: 'Iraqi Dinar', flag: '🇮🇶', locale: 'en-US' },
  { code: 'IRR', symbol: '﷼', name: 'Iranian Rial', flag: '🇮🇷', locale: 'en-US' },
  { code: 'ISK', symbol: 'kr', name: 'Iceland Krona', flag: '🇮🇸', locale: 'en-US' },
  { code: 'JMD', symbol: '$', name: 'Jamaican Dollar', flag: '🇯🇲', locale: 'en-US' },
  { code: 'JOD', symbol: 'د.ا', name: 'Jordanian Dinar', flag: '🇯🇴', locale: 'en-US' },
  { code: 'JPY', symbol: '¥', name: 'Yen', flag: '🇯🇵', locale: 'ja-JP' },
  { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling', flag: '🇰🇪', locale: 'en-US' },
  { code: 'KGS', symbol: 'с', name: 'Som', flag: '🇰🇬', locale: 'en-US' },
  { code: 'KHR', symbol: '៛', name: 'Riel', flag: '🇰🇭', locale: 'en-US' },
  { code: 'KMF', symbol: 'CF', name: 'Comorian Franc ', flag: '🇰🇲', locale: 'en-US' },
  { code: 'KPW', symbol: '₩', name: 'North Korean Won', flag: '🇰🇵', locale: 'en-US' },
  { code: 'KRW', symbol: '₩', name: 'Won', flag: '🇰🇷', locale: 'en-US' },
  { code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar', flag: '🇰🇼', locale: 'en-US' },
  { code: 'KYD', symbol: '$', name: 'Cayman Islands Dollar', flag: '🇰🇾', locale: 'en-US' },
  { code: 'KZT', symbol: '₸', name: 'Tenge', flag: '🇰🇿', locale: 'en-US' },
  { code: 'LAK', symbol: '₭', name: 'Lao Kip', flag: '🇱🇦', locale: 'en-US' },
  { code: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound', flag: '🇱🇧', locale: 'en-US' },
  { code: 'LKR', symbol: 'Rs', name: 'Sri Lanka Rupee', flag: '🇱🇰', locale: 'en-US' },
  { code: 'LRD', symbol: '$', name: 'Liberian Dollar', flag: '🇱🇷', locale: 'en-US' },
  { code: 'LSL', symbol: 'L', name: 'Loti', flag: '🇱🇸', locale: 'en-US' },
  { code: 'LYD', symbol: 'ل.د', name: 'Libyan Dinar', flag: '🇱🇾', locale: 'en-US' },
  { code: 'MAD', symbol: 'DH', name: 'Moroccan Dirham', flag: '🇲🇦', locale: 'en-US' },
  { code: 'MDL', symbol: 'MDL', name: 'Moldovan Leu', flag: '🇲🇩', locale: 'en-US' },
  { code: 'MGA', symbol: 'MGA', name: 'Malagasy Ariary', flag: '🇲🇬', locale: 'en-US' },
  { code: 'MKD', symbol: 'ден', name: 'Denar', flag: '🇲🇰', locale: 'en-US' },
  { code: 'MMK', symbol: 'K', name: 'Kyat', flag: '🇲🇲', locale: 'en-US' },
  { code: 'MNT', symbol: '₮', name: 'Tugrik', flag: '🇲🇳', locale: 'en-US' },
  { code: 'MOP', symbol: 'MOP$', name: 'Pataca', flag: '🇲🇴', locale: 'en-US' },
  { code: 'MRU', symbol: 'UM', name: 'Ouguiya', flag: '🇲🇷', locale: 'en-US' },
  { code: 'MUR', symbol: '₨', name: 'Mauritius Rupee', flag: '🇲🇺', locale: 'en-US' },
  { code: 'MVR', symbol: 'Rf', name: 'Rufiyaa', flag: '🇲🇻', locale: 'en-US' },
  { code: 'MWK', symbol: 'MK', name: 'Malawi Kwacha', flag: '🇲🇼', locale: 'en-US' },
  { code: 'MXN', symbol: 'MX$', name: 'Mexican Peso', flag: '🇲🇽', locale: 'en-US' },
  { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit', flag: '🇲🇾', locale: 'en-US' },
  { code: 'MZN', symbol: 'MT', name: 'Mozambique Metical', flag: '🇲🇿', locale: 'en-US' },
  { code: 'NAD', symbol: '$', name: 'Namibia Dollar', flag: '🇳🇦', locale: 'en-US' },
  { code: 'NGN', symbol: '₦', name: 'Naira', flag: '🇳🇬', locale: 'en-US' },
  { code: 'NIO', symbol: 'C$', name: 'Cordoba Oro', flag: '🇳🇮', locale: 'en-US' },
  { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', flag: '🇧🇻', locale: 'en-US' },
  { code: 'NPR', symbol: 'Rs', name: 'Nepalese Rupee', flag: '🇳🇵', locale: 'en-US' },
  { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', flag: '🇳🇿', locale: 'en-US' },
  { code: 'OMR', symbol: '﷼', name: 'Rial Omani', flag: '🇴🇲', locale: 'en-US' },
  { code: 'PAB', symbol: 'B/.', name: 'Balboa', flag: '🇵🇦', locale: 'en-US' },
  { code: 'PEN', symbol: 'S/', name: 'Sol', flag: '🇵🇪', locale: 'en-US' },
  { code: 'PGK', symbol: 'K', name: 'Kina', flag: '🇵🇬', locale: 'en-US' },
  { code: 'PHP', symbol: '₱', name: 'Philippine Peso', flag: '🇵🇭', locale: 'en-US' },
  { code: 'PKR', symbol: '₨', name: 'Pakistan Rupee', flag: '🇵🇰', locale: 'en-US' },
  { code: 'PLN', symbol: 'zł', name: 'Zloty', flag: '🇵🇱', locale: 'en-US' },
  { code: 'PYG', symbol: '₲', name: 'Guarani', flag: '🇵🇾', locale: 'en-US' },
  { code: 'QAR', symbol: '﷼', name: 'Qatari Rial', flag: '🇶🇦', locale: 'en-US' },
  { code: 'RON', symbol: 'lei', name: 'Romanian Leu', flag: '🇷🇴', locale: 'en-US' },
  { code: 'RSD', symbol: 'дин.', name: 'Serbian Dinar', flag: '🇷🇸', locale: 'en-US' },
  { code: 'RUB', symbol: '₽', name: 'Russian Ruble', flag: '🇷🇺', locale: 'en-US' },
  { code: 'RWF', symbol: 'FRw', name: 'Rwanda Franc', flag: '🇷🇼', locale: 'en-US' },
  { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal', flag: '🇸🇦', locale: 'en-US' },
  { code: 'SBD', symbol: '$', name: 'Solomon Islands Dollar', flag: '🇸🇧', locale: 'en-US' },
  { code: 'SCR', symbol: '₨', name: 'Seychelles Rupee', flag: '🇸🇨', locale: 'en-US' },
  { code: 'SDG', symbol: 'ج.س.', name: 'Sudanese Pound', flag: '🇸🇩', locale: 'en-US' },
  { code: 'SEK', symbol: 'kr', name: 'Swedish Krona', flag: '🇸🇪', locale: 'en-US' },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', flag: '🇸🇬', locale: 'en-US' },
  { code: 'SHP', symbol: '£', name: 'Saint Helena Pound', flag: '🇸🇭', locale: 'en-US' },
  { code: 'SLE', symbol: 'Le', name: 'Leone', flag: '🇸🇱', locale: 'en-US' },
  { code: 'SOS', symbol: 'S', name: 'Somali Shilling', flag: '🇸🇴', locale: 'en-US' },
  { code: 'SRD', symbol: '$', name: 'Surinam Dollar', flag: '🇸🇷', locale: 'en-US' },
  { code: 'SSP', symbol: '£', name: 'South Sudanese Pound', flag: '🇸🇸', locale: 'en-US' },
  { code: 'STN', symbol: 'Db', name: 'Dobra', flag: '🇸🇹', locale: 'en-US' },
  { code: 'SVC', symbol: 'SVC', name: 'El Salvador Colon', flag: '🇸🇻', locale: 'en-US' },
  { code: 'SYP', symbol: '£', name: 'Syrian Pound', flag: '🇸🇾', locale: 'en-US' },
  { code: 'SZL', symbol: 'E', name: 'Lilangeni', flag: '🇸🇿', locale: 'en-US' },
  { code: 'THB', symbol: '฿', name: 'Baht', flag: '🇹🇭', locale: 'en-US' },
  { code: 'TJS', symbol: 'SM', name: 'Somoni', flag: '🇹🇯', locale: 'en-US' },
  { code: 'TMT', symbol: 'T', name: 'Turkmenistan New Manat', flag: '🇹🇲', locale: 'en-US' },
  { code: 'TND', symbol: 'DT', name: 'Tunisian Dinar', flag: '🇹🇳', locale: 'en-US' },
  { code: 'TOP', symbol: 'T$', name: 'Pa’anga', flag: '🇹🇴', locale: 'en-US' },
  { code: 'TRY', symbol: '₺', name: 'Turkish Lira', flag: '🇹🇷', locale: 'en-US' },
  { code: 'TTD', symbol: '$', name: 'Trinidad and Tobago Dollar', flag: '🇹🇹', locale: 'en-US' },
  { code: 'TWD', symbol: 'NT$', name: 'New Taiwan Dollar', flag: '🇹🇼', locale: 'en-US' },
  { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling', flag: '🇹🇿', locale: 'en-US' },
  { code: 'UAH', symbol: '₴', name: 'Hryvnia', flag: '🇺🇦', locale: 'en-US' },
  { code: 'UGX', symbol: 'USh', name: 'Uganda Shilling', flag: '🇺🇬', locale: 'en-US' },
  { code: 'USD', symbol: '$', name: 'US Dollar', flag: '🇺🇸', locale: 'en-US' },
  { code: 'UYU', symbol: '$U', name: 'Peso Uruguayo', flag: '🇺🇾', locale: 'en-US' },
  { code: 'UZS', symbol: 'лв', name: 'Uzbekistan Sum', flag: '🇺🇿', locale: 'en-US' },
  { code: 'VED', symbol: 'Bs', name: 'Bolívar Soberano', flag: '🇻🇪', locale: 'en-US' },
  { code: 'VES', symbol: 'Bs', name: 'Bolívar Soberano', flag: '🇻🇪', locale: 'en-US' },
  { code: 'VND', symbol: '₫', name: 'Dong', flag: '🇻🇳', locale: 'en-US' },
  { code: 'VUV', symbol: 'VT', name: 'Vatu', flag: '🇻🇺', locale: 'en-US' },
  { code: 'WST', symbol: 'WS$', name: 'Tala', flag: '🇼🇸', locale: 'en-US' },
  { code: 'XAF', symbol: 'FCFA', name: 'CFA Franc BEAC', flag: '🇨🇲', locale: 'en-US' },
  { code: 'XAG', symbol: 'oz', name: 'Silver', flag: '🥈', locale: 'en-US' },
  { code: 'XAU', symbol: 'oz', name: 'Gold', flag: '🥇', locale: 'en-US' },
  { code: 'XCD', symbol: 'XCD', name: 'East Caribbean Dollar', flag: '🇦🇬', locale: 'en-US' },
  { code: 'XDR', symbol: 'SDR', name: 'SDR (Special Drawing Right)', flag: '🌐', locale: 'en-US' },
  { code: 'XOF', symbol: 'CFA', name: 'CFA Franc BCEAO', flag: '🇸🇳', locale: 'en-US' },
  { code: 'XPD', symbol: 'oz', name: 'Palladium', flag: '💎', locale: 'en-US' },
  { code: 'XPF', symbol: 'XPF', name: 'CFP Franc', flag: '🇵🇫', locale: 'en-US' },
  { code: 'XPT', symbol: 'oz', name: 'Platinum', flag: '💎', locale: 'en-US' },
  { code: 'YER', symbol: '﷼', name: 'Yemeni Rial', flag: '🇾🇪', locale: 'en-US' },
  { code: 'ZAR', symbol: 'R', name: 'Rand', flag: '🇱🇸', locale: 'en-US' },
  { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha', flag: '🇿🇲', locale: 'en-US' },
  { code: 'ZWG', symbol: 'ZiG', name: 'Zimbabwe Gold', flag: '🇿🇼', locale: 'en-US' },
];

export const CURRENCY_MAP: Record<string, CurrencyInfo> = CURRENCIES.reduce((acc, c) => {
  acc[c.code] = c;
  return acc;
}, {} as Record<string, CurrencyInfo>);